name: Xiaogang Dong API Key

on:
  push:
    branches:
      - main

jobs:
  my_secret_key:
    runs-on: ubuntu-latest
    env: 
      MY_API_KEY: ${{ vars.MY_API_KEY }}
    steps:
      - name: Print the API Key
        run: echo "API Key is ${{ env.MY_API_KEY }}"
