name: Xiaogang Dong API Key

on:
  push:
    branches:
      - main

jobs:
  my_secret_key:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.MY_API_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check my secret key
        run: |
          echo "My Env API Key is: $MY_API_KEY"
