name: Xiaogang Dong API Key

on:
  push:
    branches:
      - main

jobs:
  my_secret_key:
    runs-on: ubuntu-latest
    steps:
      - name: output my private API Key
        run: echo "API Key is ${{ secrets.DONG_API_KEY }}"
