name: Xiaogang Dong API Key

on:
  push:
    branches:
      - main

jobs:
  my_secret_key:
    runs-on: ubuntu-latest
    steps:
      - name: Print the API Key
        run: echo "API Key is ${{ vars.MY_API_KEY }}"
