name: Unit Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:                                       # create job called "test" to perform Unit Tests 
  test:  
    runs-on: ubuntu-latest.                 # this job will run on the latest version of Ubuntu
    steps:                                  # list of steps that need to be taken when Unit Tests is triggered 
    - uses: actions/checkout@v3             # check out code from repository
    - name: run my one-line script             
    - name: run my multiple-line script             
          echo Hello Xiaogang Dong! 
          echo It's a brand new day! 
