name: Unit Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:                                       # Create job called "test" to perform Unit Tests 
  test:  
    runs-on: ubuntu-latest                  # This job will run on the latest version of Ubuntu
    steps:                                  # List of steps that need to be taken when Unit Tests is triggered 
      - uses: actions/checkout@v3           # Check out code from repository
      - name: Run my one-line script
        run: |
          echo Hello! I am a one-line greeting!
      - name: Run my multiple-line script
        run: |
          echo Hello Xiaogang Dong! 
          echo It is a brand new day!
