name: Unit Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:                                       # Create job called "test" to perform Unit Tests 
  test:  
    runs-on: ubuntu-latest                  # This job will run on the latest version of Ubuntu
    steps:                                  # List of steps that need to be taken when Unit Tests is triggered 
      - uses: actions/checkout@v3           # Check out code from repository
      - name: Run my one-line script
        run: |
          echo Hello! I am a one-line greeting!
      - name: Run my multiple-line script
        run: |
          echo Hello Xiaogang Dong! 
          echo It is a brand new day!
      - name: Install dependencies            # install all dependencies needed for Unit Tests (ex. Jest) 
        run: npx yarn    
        working-directory: ./Lab1 
      - uses: actions/download-artifact@v3    # download compiled code from build and make it available for Unit Tests 
        with:
          path: dist
      - name: Run Tests                       # run Unit Tests using Jest
        run: npx yarn test
        working-directory: ./Lab1 
      - name: Build project
        run: npx yarn build
        working-directory: ./Lab1 
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./Lab1/dist/
      - name: Run Style Checks
        run: npm run style
